permissions:
  id-token: write
  contents: read

name: Build

on:
  pull_request:
    types:
      - closed

jobs:

  if-merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: docker-test
      AWS_REGION: us-west-2
      AWS_ACCOUNT_ID: 707768507475
      ECR_REPO_NAME: eks-demo
      IAM_ROLE: github-actions

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE
        aws-region: $AWS_REGION

    - name: Build the Docker image
      run: docker build -t $DOCKER_IMAGE_NAME .

    - name: Push Docker image to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        docker tag $DOCKER_IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
